config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'todo_lists#index'

  resources :todo_lists, except: %i[new edit] do
    resources :tasks, shallow: true, only: %i[create update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo_list

  validates :description, presence: true, uniqueness: { scope: :todo_list_id }

  default_scope { order(expiration_time: :asc) }
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :user_id }

  default_scope { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todo_lists

  def author?(object)
    object.user_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_todo_list, only: :create
  before_action :set_task, only: %i[update destroy]
  before_action :check_author, only: %i[update destroy]

  def create
    @task = @todo_list.tasks.new(task_params)
    flash.now[:notice] = 'Task successfully created.' if @task.save
  end

  def update
    flash.now[:notice] = 'Task successfully updated.' if @task.update(task_params)
  end

  def destroy
    flash.now[:notice] = 'Task successfully deleted.' if @task.destroy
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def check_author
    redirect_to root_path, alert: 'You are not author' unless current_user.author?(@task.todo_list)
  end

  def task_params
    params.require(:task).permit(:description, :expiration_time, :done)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[show update destroy]
  before_action :check_author, only: %i[show update destroy]

  def index
    @todo_lists = current_user.todo_lists
    @todo_list = TodoList.new
  end

  def show
    @tasks = @todo_list.tasks
    @task = Task.new
  end

  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)
    flash.now[:notice] = 'Todo List successfully created.' if @todo_list.save
  end

  def update
    flash.now[:notice] = 'Todo List successfully updated.' if @todo_list.update(todo_list_params)
  end

  def destroy
    flash.now[:notice] = 'Todo List successfully deleted.' if @todo_list.destroy
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  def check_author
    redirect_to root_path, alert: 'You are not author' unless current_user.author?(@todo_list)
  end

  def todo_list_params
    params.require(:todo_list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end

  def github_url(author, repo)
    link_to 'TODO', "https://github.com/#{author}/#{repo}", target: '_blank', rel: 'noopener'
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/_footer.html.erb
<hr>
<footer class="footer">
  <small>
    Current time: <%= Time.now.strftime("%H:%M") %> |
    Author - Serhii Nakul |
    Project - <%= github_url("sergeynakul", "todo") %> |
    Simple TODO-list application
  </small>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-light mb-3">
  <%= link_to 'TODO lists', root_path, class: 'navbar-brand' %>
  <span class="navbar-text">
    <% if user_signed_in? %>
      Welcome <%= current_user.email %> | <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %> | <%= link_to 'Registration', new_user_registration_path %>
    <% end %>
  </span>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <div class="flash">
        <%= render partial: 'shared/flash', flash: flash %>
      </div>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource&.errors.present? %>
  <%= content_tag :div, class: "resource-errors", data: { resource_id: resource.id } do %>
    <ul>
      <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
      <%= msg %>
      <button class="close" data-dismiss="alert">x</button>
    </div>
  <% end %>
</div>

app/views/tasks/_form_inline.html.erb
<%= content_tag :div, class: 'errors', data: { task_id: task.id } do %>
  <%= render 'shared/errors', resource: @task %>
<% end %>
<%= form_with model: task.persisted? ? task : [@todo_list, task],
              class: task.persisted? ? 'form-inline form-inline-update hide' : 'form-inline form-inline-create',
              data: { task_id: task.id } do |form| %>
  <%= form.text_area :description, class: 'form-control mb-2 mr-sm-2', placeholder: 'Description', cols: "60" %>
  <%= form.label :expiration_time, 'Deadline', class: "my-1 mr-2" %>
  <%= form.datetime_field :expiration_time, class: 'form-control mb-2 mr-sm-2' %>
  <% if task.persisted? %>
    <%= form.label :done, class: "form-check-label mr-2" %>
    <%= form.check_box :done, class: "form-check-input mr-2" %>
  <% end %>
  <%= form.submit class: 'btn btn-primary mb-2' %>
<% end %>

app/views/tasks/_index.html.erb
<h2>Tasks</h2>

<div class="create-errors">
  <%= render 'shared/errors', resource: @task %>
</div>

<%= render 'tasks/form_inline', task: @task %>

<div class='tasks'>
  <%= render @tasks %>
</div>

app/views/tasks/_task.html.erb
<%= content_tag :div, class: 'task border border-primary rounded mb-2 p-2', data: { task_id: task.id } do %>
  <%= content_tag :div, class: 'task_inner', data: { task_id: task.id } do %>
    <p>Description: <%= task.description %></p>
    <p>Deadline: <%= task.expiration_time %></p>
    <p>Done? <%= task.done %></p>
  <% end %>
  <%= render 'tasks/form_inline', task: task == @task ? @task : task %>
  <%= link_to 'Edit', '#', data: { task_id: task.id }, class: 'form-inline-link' %> | 
  <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
<% end %>

app/views/tasks/create.js.erb
$('.flash').html('<%= j render partial: 'shared/flash', flash: notice %>');
$('.create-errors').html('<%= j render 'shared/errors', resource: @task %>');

<% if @task.persisted? %>
  $(".tasks").append("<%= j render @task %>");
  $("#task_description").val("");
  $("#task_expiration_time").val("");
<% end %>

app/views/tasks/destroy.js.erb
$('.flash').html('<%= j render partial: 'shared/flash', flash: notice %>');
$('.task[data-task-id="' + <%= @task.id %> + '"]').remove();

app/views/tasks/update.js.erb
$('.flash').html('<%= j render partial: 'shared/flash', flash: notice %>');
$('.errors[data-task-id="' + <%= @task.id %> + '"]').html('<%= j render 'shared/errors', resource: @task %>');

<% if !@task.errors.present? %>
  $('.task[data-task-id="' + <%= @task.id %> + '"]').replaceWith('<%= j render @task %>');
<% end %>

app/views/todo_lists/_form_inline.html.erb
<%= content_tag :div, class: 'errors', data: { todo_list_id: todo_list.id } do %>
  <%= render 'shared/errors', resource: todo_list %>
<% end %>
<%= form_with model: todo_list,
              class: todo_list.persisted? ? 'form-inline form-inline-update hide' : 'form-inline form-inline-create',
              data: { todo_list_id: todo_list.id } do |form| %>
  <%= form.text_field :title, class: 'form-control mb-2 mr-sm-2', placeholder: 'Todo list title' %>
  <%= form.submit class: 'btn btn-primary mb-2' %>
<% end %>

app/views/todo_lists/_todo_list.html.erb
<%= content_tag :tr, data: { todo_list_id: todo_list.id } do %>
  <td class="align-middle">
    <%= content_tag :span, todo_list.title, class: 'todo-list-title', data: { todo_list_id: todo_list.id } %>
    <%= render 'todo_lists/form_inline', todo_list: todo_list == @todo_list ? @todo_list : todo_list %>
  </td>
  <td class="align-middle"><%= link_to 'Show', todo_list_path(todo_list) %></td>
  <td class="align-middle">
    <%= link_to 'Edit', '#', data: { todo_list_id: todo_list.id }, class: 'form-inline-link' %>
  </td>
  <td class="align-middle"><%= link_to 'Delete', todo_list_path(todo_list), method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
<% end %>

app/views/todo_lists/create.js.erb
$('.flash').html('<%= j render partial: 'shared/flash', flash: notice %>');
$('.create-errors').html('<%= j render 'shared/errors', resource: @todo_list %>');

<% if @todo_list.persisted? %>
  $('.table > tbody').append("<%= j render @todo_list %>");
  $("#todo_list_title").val("");
<% end %>

app/views/todo_lists/destroy.js.erb
$('.flash').html('<%= j render partial: 'shared/flash', flash: notice %>');
$('tr[data-todo-list-id="' + <%= @todo_list.id %> + '"]').remove();

app/views/todo_lists/index.html.erb
<div class="row">
  <div class="col">
    <h1>Your TODO lists</h1>

    <div class="create-errors">
      <%= render 'shared/errors', resource: @todo_list %>
    </div>

    <%= render 'todo_lists/form_inline', todo_list: @todo_list %>

    <table class="table">
      <tr>
        <th>Title</th>
        <th colspan="3">Actions</th>
      </tr>
      <%= render @todo_lists %>
    </table>
  </div>
</div>

app/views/todo_lists/show.html.erb
<div class="row">
  <div class="col">
    <h1><%= @todo_list.title %></h1>

    <%= render 'tasks/index' %>

    <p><%= link_to 'Back', todo_lists_path %></p>
  </div>
</div>

app/views/todo_lists/update.js.erb
$('.flash').html('<%= j render partial: 'shared/flash', flash: notice %>');
$('.errors[data-todo-list-id="' + <%= @todo_list.id %> + '"]').html('<%= j render 'shared/errors', resource: @todo_list %>');

<% if !@todo_list.errors.present? %>
  $('tr[data-todo-list-id="' + <%= @todo_list.id %> + '"]').replaceWith('<%= j render @todo_list %>');
<% end %>